### PR TITLE
chore: Make create company form mobile friendly

### PR DESCRIPTION
**Pull request by TerrellLinnell**
Made all sections responsive to screen size changes, this includes a change up in the preview window, fixed form validation issue where touching some fields did not set them as touched fields, categories had to use onFocus instead of onBlur, reworked form level error to look better with long error messages

### CODE REVIEW

**Comment by medelman17** [comment]
@TerrellLinnell -- you want my review on this?

**Comment by TerrellLinnell** [comment]
should be good now I had found a couple things I needed to fix before review

**Comment by medelman17** [comment]
But why review this PR? I'll review the PR for #84

**Review by medelman17 — APPROVED** [review]
Will review on PR to develop

**Comment by TerrellLinnell** [comment]
i guess i assigned out of habit

**Pull request merged**
